name: Portfolio CI/CD
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  verify:
    name: Verify Code
    uses: ./.github/workflows/verify.yml

  deploy-dev:
    name: Deploy to Development
    if: github.event_name == 'pull_request'
    needs: verify
    uses: ./.github/workflows/deploy.yml
    with:
      AWSAccountId: "${{ vars.AWS_ACCOUNT_ID }}"
      BucketName: "dev.${{ vars.BASE_URL }}"
      Environment: "dev"
    secrets: inherit

  deploy-prod:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: verify
    uses: ./.github/workflows/deploy.yml
    with:
      AWSAccountId: "${{ vars.AWS_ACCOUNT_ID }}"
      Environment: "prod"
      BucketName: "${{ vars.BASE_URL }}"
    secrets: inherit
