name: Verify
on:
  pull_request: {}
  workflow_dispatch: {}
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string

jobs:
  cloudformation-lint:
    name: Cloudformation Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup CFN lint
        uses: scottbrenner/cfn-lint-action@v2

      - name: cfn-lint
        run: cfn-lint cloudformation.template.yml

  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Validate code
        run: npm run lint

      - name: Build Website
        run: npm run build

      - name: Upload Website Artifact
        if: inputs.Environment
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: out
          retention-days: 1
