name: Verify
on:
  workflow_call: {}

jobs:
  cloudformation-lint:
    name: Cloudformation Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup CFN lint
        uses: scottbrenner/cfn-lint-action@v2

      - name: cfn-lint
        run: cfn-lint cloudformation.template.yml

  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Check format
        run: npm run check-format

      - name: Validate code
        run: npm run lint

      - name: Build Website
        run: npm run build

      - name: Upload Website Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_id }}
          path: out
          retention-days: 1
